### PR TITLE
Minor Refactoring. Simple Modernisation and more concise/direct ReadMe.

### PR DESCRIPTION
**Pull request by ghost**
Hi Rob!

A client is asking me for some PDF related tasks and I remembered a while back that you submitted this code to the public domain. It's still impressive today and I figured I should make some sort of contribution to the effort.

Granted, all I have done is clean it up a bit. The logic is still sound. One thing I did notice, is that the preview controller wasn't working properly in modern devices, so just using web view for now. It's only a demo project anyway. The real meat, is in your class that does the drawing.

Other changes include simple modernisation of the build settings, courtesy of Xcode 7 wizard. Also enabled size classes.

I cut down the read me file so that it's easier on the eye and straight to the point. Hope that's ok. Also removed the debugging feature because it seemed to only be necessary during development i.e. the code is stable now.

If your happy with all this then please merge into your master branch. I look forward to any updates you do to this code. I'm 'watching' this repo so I will be notified!

### CODE REVIEW

**Comment by RobertAPhillips** [comment]
Hi Rob,

Please amend and contribute as much as you like. I’ll probably be making use of this code soon as I also need it in a project, so your changes and improvements will be well utilised and gratefully received.

How are you doing? What happened to the coffee we were going to have back at the beginning of the year?

Kind regards,

Robert

## 

Robert Phillips
Software Developer
Intohand Ltd
Main: +44(0)1225 475884
Mobile: +44(0)7583 392508

Office: Circus Mews House, Circus Mews, Bath, BA1 2PW
Registered Office: 37 Gt Pulteney St, Bath, BA2 4DA, UK
Registered in England and Wales
Company Registration Number 5765736

www.intohand.com http://www.intohand.com/

**Comment by rob-nash** [comment]
Ha ye! Let’s do it anytime. I got a visa application in for a one way ticket to Canada. Prob best we catch up within the next 3 weeks. Friday lunch time?

On 30 Sep 2015, at 09:57, RobertAPhillips <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Rob,

Please amend and contribute as much as you like. I’ll probably be making use of this code soon as I also need it in a project, so your changes and improvements will be well utilised and gratefully received.

How are you doing? What happened to the coffee we were going to have back at the beginning of the year?

Kind regards,

Robert

--

Robert Phillips
Software Developer
Intohand Ltd
Main: +44(0)1225 475884
Mobile: +44(0)7583 392508

Office: Circus Mews House, Circus Mews, Bath, BA1 2PW
Registered Office: 37 Gt Pulteney St, Bath, BA2 4DA, UK
Registered in England and Wales
Company Registration Number 5765736

www.intohand.com<http://www.intohand.com> <http://www.intohand.com/>

**Comment by ghost** [comment]
By the way you have to click the 'merge' button.

**Comment by RobertAPhillips** [comment]
Done and merged.

Can’t do Friday this week as I’m not in Bath. I’m next in Bath on Monday or Wednesday next week.

Kind regards,

Robert

## 

Robert Phillips
Software Developer
Intohand Ltd
Main: +44(0)1225 475884
Mobile: +44(0)7583 392508

Office: Circus Mews House, Circus Mews, Bath, BA1 2PW
Registered Office: 37 Gt Pulteney St, Bath, BA2 4DA, UK
Registered in England and Wales
Company Registration Number 5765736

www.intohand.com http://www.intohand.com/

**Comment by ghost** [comment]
Let'd do Monday lunch time.

**Comment by RobertAPhillips** [comment]
OK, it’s a date. What time?

Kind regards,

Robert

## 

Robert Phillips
Software Developer
Intohand Ltd
Main: +44(0)1225 475884
Mobile: +44(0)7583 392508

Office: Circus Mews House, Circus Mews, Bath, BA1 2PW
Registered Office: 37 Gt Pulteney St, Bath, BA2 4DA, UK
Registered in England and Wales
Company Registration Number 5765736

www.intohand.com http://www.intohand.com/

**Comment by ghost** [comment]
12 ?

On 30 Sep 2015, at 11:57, RobertAPhillips <notifications@github.com<mailto:notifications@github.com>> wrote:

OK, it’s a date. What time?

Kind regards,

Robert

## 

Robert Phillips
Software Developer
Intohand Ltd
Main: +44(0)1225 475884
Mobile: +44(0)7583 392508

Office: Circus Mews House, Circus Mews, Bath, BA1 2PW
Registered Office: 37 Gt Pulteney St, Bath, BA2 4DA, UK
Registered in England and Wales
Company Registration Number 5765736

www.intohand.comhttp://www.intohand.com http://www.intohand.com/

**Comment by RobertAPhillips** [comment]
OK, 12 it is. I’ll put it in my diary.

Kind regards,

Robert

## 

Robert Phillips
Software Developer
Intohand Ltd
Main: +44(0)1225 475884
Mobile: +44(0)7583 392508

Office: Circus Mews House, Circus Mews, Bath, BA1 2PW
Registered Office: 37 Gt Pulteney St, Bath, BA2 4DA, UK
Registered in England and Wales
Company Registration Number 5765736

www.intohand.com http://www.intohand.com/

**Pull request merged**
